[build]
  command = "ng build --configuration production"
  publish = "dist/health-sync/browser"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200